on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: Test
jobs:
  go-test:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
          check-latest: true
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Go Tests with Coverage
        run: make test
      - name: Stactic checker
        uses: dominikh/staticcheck-action@v1.3.1
        with:
          install-go: false
